version: "3.5"
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: best_practice_api
        working_dir: /var/www/laravel-best-practice
        depends_on:
            - db
        networks:
            - best_practice
        volumes:
            - .:/var/www/laravel-best-practice
    webserver:
        image: nginx:1.23
        container_name: best_practice_nginx
        working_dir: /var/www/laravel-best-practice
        depends_on:
            - app
        networks:
            - best_practice
        ports:
            - 6001:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/laravel-best-practice
    db:
        image: mysql:8.0
        container_name: best_practice_mysql
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - best_practice
        volumes:
            - /home/database/Workspace/Deploy/db_store/laravel-best-practice:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
    db_client:
        image: adminer
        container_name: best_practice_adminer
        ports:
            - 6002:8080
        networks:
            - best_practice
    redis:
        image: redis:latest
        container_name: best_practice_redis
        ports:
            - "6383:6379"
        networks:
            - best_practice
networks:
    best_practice:
        driver: bridge
